[build]
buildCommand = "apt-get update && apt-get install -y python3 python3-pip && python3 -m pip install -r requirements.txt && python3 -m pip install spacy && python3 -m spacy download en_core_web_sm"

[deploy]
startCommand = "python main_fixed.py"
healthcheckPath = "/"
healthcheckTimeout = 60
